### ISSUE TITLE
Doc tags on frontend doc creation

### ISSUE THREAD

**Issue by pieropaoli** [boonebgorges/buddypress-docs#381]
I'd like to know how to set a checkbox to associate existing doc tags to new docs; now the plugin supplies a Text Fields.
I need to change it with a checkbox where plugin suggests existing tags to be checked to classify the doc.

![tags field](https://f.cloud.github.com/assets/6849176/2319742/f9234768-a382-11e3-9b80-d0b74879bd47.JPG)

could someone help me.

Thanks a lot

**Comment by boonebgorges** [comment]
Ack, very sorry not to have responded to this.

The "associated items" feature you see on the back end is what Docs uses to link to groups, etc. It's not possible to use this for front-end customization beside this purpose. Tags are really best for this.

I'm going to close this ticket due to its age, but don't hesitate to post again if there are ongoing issues that may point to a bug in Docs.
