### ISSUE TITLE
Can't Upload Docs + Error message (compat. with BP_Group_Extension)

### ISSUE THREAD

**Issue by Mat2012** [boonebgorges/buddypress-docs#446]
This is a great plugin !

But, on my install, this error message appears after activation of the plugin:

Declaration of BP_Docs_Group_Extension::display() should be compatible with BP_Group_Extension::display($group_id = NULL) in /Applications/MAMP/htdocs/mysite/wp-content/plugins/buddypress-docs/includes/integration-groups.php on line 924

Moreover, I can't attach a document (nothing happens when I want to upload a doc).

I'm using the last version of WP and BP.

Can you help me to fix this problem ?

M.

**Comment by boonebgorges** [comment]
The error message is fixed in https://github.com/boonebgorges/buddypress-docs/commit/1744e1fbf127885b1830cd46416e98d9a951f627. It is harmless - and should not be displaying on your production site anyway - but you can patch it manually if you don't want to wait for the next release.

There are a few other reports of problems with attachments; see https://github.com/boonebgorges/buddypress-docs/issues. I can't tell what "nothing happens" means - does that mean that you click a button and nothing happens? Or that when you've selected an image to upload and clicked Upload, nothing happens? Or that the image uploads, but then is not attached to the Doc? The first place to begin debugging is by opening your JS console to see if it shows any errors.

**Comment by Mat2012** [comment]
OK, thanks for 1744e1f.

And sorry for being not specific enough in my second question.
 
I've disabled all my plugin - except BP.
I can't see any errors in my JS console.

When I click the "upload a file" button, the window opens, I can choose a file, but then, I have this error message (see image) : 
![buddypress docs 2015-03-06 16-26-08](https://cloud.githubusercontent.com/assets/1023932/6527758/928ca92e-c41d-11e4-8c66-daa4696b1388.png)
