### ISSUE TITLE
Member count in associated-goup-toggle not working

### ISSUE THREAD

**Issue by schwarzaufweiss** [boonebgorges/buddypress-docs#491]
The member count in associated-goup-toggle isn't working for me based on BP 2.3.3 and BP Docs 1.8.8 (always zero).

**Comment by boonebgorges** [comment]
This is probably the same issue as what's addressed in https://github.com/boonebgorges/buddypress-docs/pull/490. It will be fixed in 1.8.9. 

Can you say more about when this happened? Did you update BuddyPress at the same time that you updated Docs? It's not clear to me how or why this would happen.

**Comment by schwarzaufweiss** [comment]
No, not at the same time. I updated BP the moment it was released – and BP Docs just now.

**Comment by boonebgorges** [comment]
@dcavins If you get a moment, would you look over the 1.8.8 changesets to see if something would be causing groups not to populate properly in this context? I can't think of anything. It doesn't matter too much since it's fixed already for the next release, but it would be good to know if there were going to be other issues.

**Comment by dcavins** [comment]
Hi @boonebgorges, this probably broke with this changeset in BP:
https://buddypress.trac.wordpress.org/changeset/8056

The count is only returned if `populate_extras` is `true`, so `bp_docs_associated_group_summary()` is relying on the old defaults and could be fixed by calling:
`groups_get_group( 'populate_extras=true&group_id=' . $group_id );`

If populate_extras isn't set, `total_member_count` is null. :(

**Comment by boonebgorges** [comment]
Gotcha. Thanks for looking it up. Doesn't matter anymore - our way of 
doing it is just as efficient :) Good to know when BP breaks something 
downstream!

**Comment by dcavins** [comment]
This should be fixed by https://github.com/boonebgorges/buddypress-docs/commit/7bb0d0f375514428c0dece8f2fd1f4e99b9c1bf1
