### ISSUE TITLE
Comments for protected docs appear in wp-admin "Comments" widget.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#504]
Comments for doc with "read comments" set to "visible only to the doc creator" or a group-related setting are visible to subscriber-level, non group-members in the WP admin dashboard's "Comments" widget.

Issue was raised here: https://wordpress.org/support/topic/parent-for-doc-dropdown-showing-all-docs?replies=14#post-7940474

**Comment by dcavins** [comment]
Looks like the old fix was to replace the "recent comments" dashboard widget, which appears to have been replaced by the "activity" widget. Doc comments also show up in the "Comments" menu item (http://commonsdev.local/wp-admin/edit-comments.php), 

in the widget, it looks like there are two opportunities to exclude comments by modifying the `get_comments()` results or by adding a `map_cap` rule to catch this check: `current_user_can( 'read_post', $comment->comment_post_ID )`

The `current_user_can()` check sounds interesting, but how would we know that it's checking the `read_post` in a comment context, and not actually to read the post? (ugh) Although, that should be catching some of these posts anyway that the user shouldn't be able to read.

`get_comments()` does use a `post__not_in` argument, so we could brute force it like the `pre_get_posts` doc protection, I suppose.

**Comment by dcavins** [comment]
I'm having doubts about using the `pre_get_comments` hook. I'm thinking that to show the "right" set, we'd have to get all doc post IDs, then check each one using `current_user_can( 'read_comments', $doc_ID )`, since that check's the only way I can think of to check group-related statuses.

Maybe a short-term fix would be to exclude all doc-related comments from the admin area unless the user has the bp_moderate cap:
`
if ( ! is_admin() || current_user_can( 'bp_moderate' ) ) {
  return;
}
`
or more generally we could check to see if the `post_id` or `post__in` query variable is set, and given some small number, run the check against each one. What would a reasonable ceiling be?

**Comment by boonebgorges** [comment]
Groan. This is a lame problem.

It's worth noting that the Activity Dashboard widget just a symptom of the larger problem. These comments will bleed through *anywhere* where `get_comments()` is used.

This doesn't feel fundamentally different from what already happens with Doc protection in `BP_Docs_Access_Query`. The difference is that, in the case of 'read', we mirror the setting between 'bp_docs_settings' and the 'bp_docs_access' taxonomy. Maybe this means that we need something similar for 'read_comments'. Obviously, this is not a trivial amount of work, but it seems like the right way to go - and we'd be able to use most of the `BP_Docs_Access_Query` infrastructure.

**Comment by dcavins** [comment]
Yes, the cowboy solution is to add `BP_Docs_Comments_Access_Query` and new taxonomy terms to cover the comment cases. I was looking at that yesterday afternoon, and it didn't look too bad. Writing up test cases will probably be the most time-consuming part (not complaining).

The only doubt I have is that the exclude method in `BP_Docs_Access_Query` does have some efficiency problems at large scale. I've got about 25,000 docs on my site, and the db server whimpers once in a while. There should be far fewer comments in my case, but other sites with very interactive communities could have more comments than docs, I suppose.

In any case, I agree that this is the way to go.

**Comment by boonebgorges** [comment]
I don't think that we need a new BP_Docs_Comments_Access_Query. It looks 
like we'll just need a switch so that BP_Docs_Access_Query looks at the 
'bp_docs_comment_read' taxonomy instead of 'bp_docs_access'. No need to 
duplicate all the code.

Agreed on the efficiency issues. For this specific issue, I don't think 
number of comments will matter - it's still number of docs that is the 
bottleneck. ('read_comments' is a Doc-level setting, and we'll be 
passing post IDs to post__not_in.) That said, I don't know of a way to 
make this faster without rewriting a lot of stuff. A more efficient 
solution would be to store the read_comment data somewhere where we 
could JOIN the comment query against it, but this is a pretty fair 
amount of work and is likely to be fragile. Maybe worth a proof of 
concept at some point.

**Comment by dcavins** [comment]
Yes, I apologize for being totally wrong. I claim cold medicine and not looking at it since yesterday as my only excuses.

I was just starting to write a new version of `bp_docs_general_access_protection ` (`bp_docs_comment_access_protection `) hooked to `pre_get_comments` and following where it would lead. I hadn't gotten much farther than seeing what the `query_vars` looked like in various contexts. (The only variations I encountered on a vanilla site were `post_id` being set to fetch the comments for a single post and basically nothing set for the catch-all `get_comments()` usage in the dashboard and Comments list in wp-admin.) It looked a lot like the case that `BP_Docs_Access_Query` covers.

**Comment by boonebgorges** [comment]
> The only variations I encountered on a vanilla site were post_id being set to fetch the comments for a single post and basically nothing set for the catch-all get_comments() usage in the dashboard and Comments list in wp-admin.

Right. This bit is critical. Because if we're querying for a single post, then it's likely that no filtering is required. (a) If the post is not a Doc, there's nothing to do. (b) If the post *is* a Doc, it's likely that we're coming from a regular Doc page, in which case access to comments should already be controlled by the way we block the comments template from loading if the current user can't read comments. Item (b) will be a bit tricky to verify in context, but a conservative logic might look like this:

    $doc_ids = array();
    $post_ids = array_merge( $query->post_id__in, array( $query->post_id ) );
    $querying_for_specific_posts = ! empty( $post_ids );
    foreach ( $post_ids as $pid ) {
        $post = get_post( $pid );
        if ( $post && bp_docs_get_post_type_name() === $post->post_type ) {
            $doc_ids[] = $pid;
        }
    }

    if ( ! $querying_for_specific_posts || ! empty( $doc_ids ) ) {
        // do the post__not_in logic. And if $doc_ids are available, we only need to check for off-limits comments from *these* Docs, not from all possible Docs.
    }

This needs a bunch of refinement and error-checking, but does it make sense as a strategy?

**Comment by dcavins** [comment]
Yes, that makes sense. I'll do a more thorough survey of what the `query_vars` look like in various cases and report back, because I think that would help identify the cases we need to cover.

**Comment by dcavins** [comment]
This will be resolved in BP 2.0. The fix has been committed to the 2.0 branch, here is a key commit:
https://github.com/boonebgorges/buddypress-docs/commit/93082178023cda0858ed89da8874b5edbdf42bb1
