### ISSUE TITLE
Commits from 1.8.x missing in 1.9.x branch

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#516]
It looks like the following commits never made it into the 1.9.x branch: https://github.com/boonebgorges/buddypress-docs/commit/f3da2d841f4bfa4f54c2150fab1d62495787343e
https://github.com/boonebgorges/buddypress-docs/commit/1e8212e7b432c62cfff45f3c9d3e89f68d059de2
https://github.com/boonebgorges/buddypress-docs/commit/28b6fa10c4dbf72e15d555794351aef8b7056972

Maybe there are others? I just checked by comparing the commit lists, which is frankly confusing.

**Comment by boonebgorges** [comment]
It's very confusing to compare the branches. This is largely because the 
repo is so out of whack.

I suggest comparing them at the command line like this:

$ git checkout 1.9.x
$ git log ..1.8.x

This tells you the changesets that appear in 1.8.x but not in 1.9.x. 
There are surely lots of false positives there, but at least it narrows 
things down considerably.

**Comment by boonebgorges** [comment]
I've taken care of this.
