### ISSUE TITLE
Improve performance of /docs/?view=manage screen

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#517]
On a very fresh install, this screen works OK. On my local test site with a small amount of content, the screen generates 1967 queries. It appears that `bp_docs_get_folders()` is generating 1000 queries. And the walker is also generating about 1000 queries.

**Comment by boonebgorges** [comment]
A couple of pain points from upstream:

* `bp_docs_get_folders()` is not independently cached, because `get_posts()` doesn't really cache queries in any meaningful way. This may be fixed in WP some day, but not soon.
* `bp_has_groups()` doesn't cache in any helpful way, which means that the associated-group dropdowns load slowly. We can look into improving caching for group queries in BP in some not-too-distant release.

I'm wary of building any robust caching layers for upstream content, but a nonpersistent cache will probably help, so let's do that for 1.9.

**Comment by boonebgorges** [comment]
I think that this catches most of the runaway queries. Can you see whether there's big improvement (or not) on your end?

**Comment by dcavins** [comment]
Hi Boone-

This is a _huge_ improvement. On one of my test sites that couldn't load this screen at all (exhausted 256MB execution memory) it now loads very quickly, using 19MB of memory (pretty typical page load on that system) and makes 109 queries (also very typical for that system). On the test environment I wrote about above, it is loading in a couple of seconds (about 1100 queries-why the vast difference in the two environments? I'll investigate).

Thanks for chasing this down. Huge, I tell you.

**Comment by boonebgorges** [comment]
Awesome. I have literally never tried to optimize any of this. It's 
likely that many of the performance problems alluded to elsewhere and 
attributed to Docs are really because of these problems, rather than 
specific queries.

**Comment by dcavins** [comment]
My production docs library of 26,000 docs thanks you. :bow:
