### ISSUE TITLE
Pagination does not work on docs/my-groups

### ISSUE THREAD

**Issue by freiwerk** [boonebgorges/buddypress-docs#527]
Hi there,

I have found an issue in the "/docs/my-groups" page. The pagination at the end of the page directs to "/docs/page/X", so there is no way to nagivate beyong page 1 in the my-groups page.

Regards

**Comment by dcavins** [comment]
Hi freiwerk-

This was an issue in previous versions, but was fixed here:
https://github.com/boonebgorges/buddypress-docs/commit/ce486891805448430e168d8e7efdd668ce0050a2

Which version of BP Docs are you using? What style of permalink are you using on your installation?

**Comment by freiwerk** [comment]
Hi,

that's strange - I am using version 1.9.0, so the bug seems to be still there.

My installation uses mod_rewrite.

**Comment by freiwerk** [comment]
I may have an explanation: The code in the bugfix you mentioned referrs to pagination in the "group documents" page. This is working on my page. The issue I am having is the "my-groups" pagination, which shows all docs from the groups you are in.

**Comment by dcavins** [comment]
Hi Freiwerk-

Thanks for your patience; you're absolutely correct. Because your report reminded me of that other problem I didn't read it as carefully as I should have. 

"My groups" pagination is broken; the fix will be included in the next bug fix release. If you'd like to test out the fix, please see this commit: https://github.com/boonebgorges/buddypress-docs/commit/045e0491b1f0f3057f7cef22fde2cc02211c65dd

Note that if you do add this code, you'll need to flush your rewrite rules. The easiest way to do so is to visit wp-admin > Settings > Permalinks and click "Save Changes".

Thanks for your report!

**Comment by freiwerk** [comment]
Thanks, I can confirm that the code works after saving the permalinks (thanks for the hint, did not know that).

**Comment by dcavins** [comment]
Thanks for letting me know it worked for you. Very much appreciated.
