### ISSUE TITLE
Add permissions to edit doc for editors

### ISSUE THREAD

**Issue by maciejbuchert** [boonebgorges/buddypress-docs#533]
How can I add permissions to edit doc for editors ?

**Comment by boonebgorges** [comment]
Sorry for the lack of response to this ticket.

The easiest way would be to filter `bp_docs_map_meta_caps`, and map `bp_docs_edit` and other related caps to `edit_others_posts`. You may want to do this in an additive way, so that `bp_docs_edit` is granted to editors *in addition to* group admins and other users specified by the Doc settings. To do this, your own `bp_docs_map_meta_caps` filter would skip modifying the caps of anyone who has already been given the capability in question by a previous filter in buddypress-docs.

See the `bp_docs_map_meta_caps()` function for some guidance on what this kind of filter callback should look like.
