### ISSUE TITLE
Folders not working

### ISSUE THREAD

**Issue by jkb0507** [boonebgorges/buddypress-docs#564]
User are having issues creating group documents. For example, one user thought she'd created a document in the group (see attachment 1), and created a folder for “Meeting Materials” and placed the document in that folder (see attachment 2).
 
However, now when she go to the group’s documents, it says there are no documents (see attachment 3). It looks like the document just went to my “personal” documents, with access restricted to members of the group.
 
Could you advise on the best way to make sure any group documents I create actually appear in the group’s documents section? Additionally, is there a way to create folders without creating a document first?
 
![screenshot1](https://cloud.githubusercontent.com/assets/26150903/23527830/6f6ecdfc-ff65-11e6-9650-6f9c1323f55d.JPG)
![screenshot2](https://cloud.githubusercontent.com/assets/26150903/23527832/6f73dee6-ff65-11e6-89b9-41e17f95e8fd.JPG)
![screenshot3](https://cloud.githubusercontent.com/assets/26150903/23527831/6f730520-ff65-11e6-828c-405f1b421527.JPG)

**Comment by boonebgorges** [comment]
Can you share more information about your theme? My guess is that the theme provides its own template for Docs, and the template has not been updated to support group folders. Thus, since folders are not displayed on your group's Docs directory, there's no way to navigate to the Doc.

>  Additionally, is there a way to create folders without creating a document first?

Each group has a Manage Folders link, visible to group admins, when viewing the group's Docs tab. If you're not seeing it, it's probably the same issue: your theme doesn't properly support the feature.

**Comment by jkb0507** [comment]
Hi, Boone! Thanks for the info - that makes sense. We worked with a development team who customized the CBOX theme for us. I'm assuming what they built doesn't support the feature. 

![screen shot 2017-03-13 at 2 39 41 pm](https://cloud.githubusercontent.com/assets/26150903/23869865/fa043cd4-07fa-11e7-9186-b9cf8f2b7ac2.png)

**Comment by boonebgorges** [comment]
Hard to know without knowing more about the theme. Does it contain a 
file docs/docs-loop.php or buddypress/docs/docs-loop.php? If so, then 
the theme is probably, in fact, the source of the problem.
