### ISSUE TITLE
Problem with check_is_protected and nginx with https

### ISSUE THREAD

**Issue by contextinst** [boonebgorges/buddypress-docs#572]
I'm running Commons In A Box on a nginx server and getting an error in check_is_protected() (line 800 in buddypress-docs/includes/attachments.php). The error, as reported by Query Monitor is:

cURL error 60: SSL certificate problem: unable to get local issuer certificate

for: buddypress-docs plugin

from an http request of: GET http://bfn.context.org/wp-content/uploads/bp-attachments/0/test.html

from a call stack of:
WP_Http->get()
wp-includes/class-http.php:612
wp_remote_get()
wp-includes/http.php:170
BP_Docs_Attachments->check_is_protected()
wp-content/plugins/buddypress-docs/includes/attachments.php:847
BP_Docs_Attachments->admin_notice_init()
wp-content/plugins/buddypress-docs/includes/attachments.php:721
do_action('admin_init')
wp-includes/plugin.php:453

In my nginx config, I've included the recommeded:

### Buddypress rewrite rule
	location /wp-content/uploads/bp-attachments/ {
		rewrite ^.*uploads/bp-attachments/([0-9]+)/(.*) /?p=$1&bp-attachment=$2 permanent;
	}

Any ideas about where the problem lies?

I don't have this issue with the same site running on Apache with http.

**Comment by boonebgorges** [comment]
Hi @contextinst -

I don't think this issue is specific to BuddyPress Docs or to nginx. It's just coming up in this context because cURL is making an HTTPS self-request in a way that's exposing a misconfiguration. I think you just need to install a recent CA bundle for cURL. See eg https://www.experts-exchange.com/questions/28996416/curl-SSL-certificate-unable-to-get-local-issuer-certificate.html

Let me know if this helps.

**Comment by contextinst** [comment]
Thanks, @boonebgorges. That does help and it does look like it is a configuration issue. Installing the CA bundle doesn't fix it but since we have the bp-attachments directory protected, it's not a practical issue for us.
