### ISSUE TITLE
Non-member editing a group doc will break group association.

### ISSUE THREAD

**Issue by dcavins** [boonebgorges/buddypress-docs#627]
If a doc is set to be associated with a group but is editable by any logged-in user, when a non-group member edits the doc, the group association (and maybe the folder association) will be lost. I thought we had addressed this already, or maybe just a similar situation.

**Comment by boonebgorges** [comment]
Yeah, it sounds vaguely familiar. Maybe 68ae526cf100162e9eeaf05044bc158bf702e3fd ?

This kind of check https://github.com/boonebgorges/buddypress-docs/blob/f90c4258cd18dbe100a208f8e853026faa5f8256/includes/functions.php#L1130 is meant to prevent unlinking. But I'm guessing that what's happening is that associated group dropdown is being shown, but the current group is not showing up in the dropdown since the logged-in user is not a member. If this is the case, we should have a special case that includes the currently associated group in the dropdown even if the user doesn't have the associate_with_group right within that group. Does that seem right?

**Comment by dcavins** [comment]
Per conversation with Boone, we've decided to allow the group association to be changed if the current editor can associate items to the group that currently houses this item.

Change will be that the group association meta box will be displayed, though the select will be `disabled`. On the back end, a check will be made before allowing the association to be updated.

**Comment by dcavins** [comment]
Ha, we solved this years ago and I have no idea what I saw that made me think this was broken. I can't reproduce, so I'm closing this issue.
