### ISSUE TITLE
Change Max File Size??

### ISSUE THREAD

**Issue by MarkRA312** [boonebgorges/buddypress-docs#666]
It only allows 2MB uploads. I have the wordpress  backend media uploader set to 25MB. That didn't fix it.

How can I modify?

**Comment by boonebgorges** [comment]
Is it possible to upload files larger than 2MB at Dashboard > Media? It's possible that your server config doesn't allow for these large uploads (`upload_max_filesize` in php.ini, etc)

**Comment by MarkRA312** [comment]
Well, while it's true that the default is 2MB, I changed the (upload_max_filesize) so that it accepts files up to 25MB. HOWEVER, that only changed the wordpress backend uploader (media). The BP Docs uploader still is limited to 2MB.

**Comment by boonebgorges** [comment]
When you say "still is limited to 2MB", can you provide exact details? Exactly what are you trying to do, and exactly what do you see? What do the error messages say, and where do they appear?

**Comment by MarkRA312** [comment]
The plugin won't allow me to upload files larger than 2MB. (But I can do it everywhere else). If you try to, it says "[file name] exceeds the maximum upload size for this site."

See screenshots
https://www.awesomescreenshot.com/image/4496966/7e355046f10346e78388d361b58153d6
http://tinyurl.com/wjmrduv

**Comment by MarkRA312** [comment]
But like I said, my backend media uploader has a size limit of 25MB

**Comment by boonebgorges** [comment]
Thanks. Can you specify exactly where in the WP Dashboard you're changing the max upload size?

**Comment by MarkRA312** [comment]
Yes, it's the php.ini file in the WP-Admin directory. 

`upload_max_filesize = 25M
post_max_size = 25M
memory_limit = 15M`

**Comment by boonebgorges** [comment]
Assuming you're not running Multisite, WordPress gets this information directly from your PHP configuration:
https://github.com/WordPress/wordpress-develop/blob/90a8a6adf6b055142a4575d6d5b0d1c52a13c822/src/wp-includes/media-template.php#L282
https://github.com/WordPress/wordpress-develop/blob/90a8a6adf6b055142a4575d6d5b0d1c52a13c822/src/wp-includes/media.php#L3192

Since you're seeing the higher limit in the Dashboard, we can assume that your PHP config settings are correct (though note that the wp-admin directory is not the place for `php.ini`). 

So the remaining explanation is that something is modifying the available upload space on the front end, probably using the `upload_size_limit` filter. BuddyPress Docs does not do this. It's possible you're running another plugin that does - a quick search on a couple of local WP installs suggests that a few popular plugins do so (buddydrive, wp-user-avatars, ultimate-branding-files - see https://github.com/search?q=add_filter+%22%27upload_size_limit%27%22&type=Code for a rough search). You might want to check whether you're using a plugin that does this.

**Comment by MarkRA312** [comment]
I see. Okay I'll take a look. Thanks for helping!
